ci(fix?)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -34,14 +34,17 @@ jobs:
         run: |
           # Install Semantic Release and extract the new version
           semantic_release_output=$(npx semantic-release --dry-run)
-          no_new_version=$(semantic_release_output | grep -oP "There are no relevant changes, so no new version is released")
-          new_version=$(semantic_release_output | grep -oP 'The next release version is \K\d+\.\d+\.\d+')' > new_version.txt)
-          if [ -z "$no_new_version" ]; then
-          echo "No new version is released"
-          exit 1
+          no_new_version=$(echo "$semantic_release_output" | grep -oP "There are no relevant changes, so no new version is released")
+          new_version=$(echo "$semantic_release_output" | grep -oP 'The next release version is \K\d+\.\d+\.\d+')
+
+          if [ -n "$no_new_version" ]; then
+            echo "No new version is released"
+            exit 1
+          fi
+
           if [ -z "$new_version" ]; then
-          echo "Failed to extract the new version from Semantic Release output."
-          exit 1
+            echo "Failed to extract the new version from Semantic Release output."
+            exit 1
           fi
 
           # Use npm version to update the package.json
